### ISSUE TITLE
How are data dependent hyperparameters handled?

### ISSUE THREAD

**Issue by jakob-r** [pfistfl/OMLRandomBotv2#2]
E.g. mtry is dependent of p (numer of features) which is usually no problem because p is more or less fixed as we don't do feature selection.

However this is different for n (number of observations). Looking at min.node.size we see that this might be set according to n. This is also done in the Bot v1.
Unfortunately the n is not fixed, when we do resampling. This was not respected in Bot v1.

See: https://github.com/ja-thomas/OMLbots/issues/45

**Comment by pfistfl** [comment]
This is indeed a very good point.

So yeah, we can obviously incorporate the fact that we do 10-fold CV.
But then this would be hardcoded.

There is no real option to do this depending on the actual task size?

**Comment by jakob-r** [comment]
Not in mlr. But as the validation indexes are stored in the openml task you can get the n from there.

**Comment by pfistfl** [comment]
Will do that for now.

**Comment by pfistfl** [comment]
So this is really ugly, because now I might have a different `n` in each split.

**Comment by jakob-r** [comment]
Yes but this little difference might be negligible?

**Comment by pfistfl** [comment]
hope so, using `min(sapply(oml.task$mlr.rin$train.inds, length))` for now.

**Comment by jakob-r** [comment]
Looks good enough

**Comment by pfistfl** [comment]
Guess we can close this for now
