### ISSUE TITLE
Parallelization

### ISSUE THREAD

**Issue by pfistfl** [pfistfl/OMLRandomBotv2#3]
@ja-thomas Do we have to limit internal parallelization in xgboost, ranger etc. manually ?

**Comment by ja-thomas** [comment]
AFAIK the defaults in mlr should be set such that no internal parallelization is used.

but we should ensure, and set it explicitly as well

**Comment by pfistfl** [comment]
This is  for example not set in (https://github.com/mlr-org/mlr/blob/master/R/RLearner_classif_xgboost.R)

**Comment by ja-thomas** [comment]
yes, it **should** :)

so we have to set it from our side anyways

**Comment by pfistfl** [comment]
This should be solved now.
